/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiKeyDto { 
    id: string;
    name: string;
    /**
     * First few characters of the key, for identification — the rest is never shown again
     */
    prefix: string;
    createdAt: string;
    lastUsedAt: string | null;
    revokedAt: string | null;
}

