/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangeVisibilityDto { 
    visibility: ChangeVisibilityDto.VisibilityEnum;
}
export namespace ChangeVisibilityDto {
    export const VisibilityEnum = {
        Public: 'public',
        Unlisted: 'unlisted',
        Private: 'private'
    } as const;
    export type VisibilityEnum = typeof VisibilityEnum[keyof typeof VisibilityEnum];
}


