/**
 * MCP Bridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateMarketPlaceItemDto { 
    name: string;
    /**
     * Rich text (HTML) — rendered sanitized by the client
     */
    description?: string;
    visibility?: CreateMarketPlaceItemDto.VisibilityEnum;
}
export namespace CreateMarketPlaceItemDto {
    export const VisibilityEnum = {
        Public: 'public',
        Unlisted: 'unlisted',
        Private: 'private'
    } as const;
    export type VisibilityEnum = typeof VisibilityEnum[keyof typeof VisibilityEnum];
}


