/**
 * MCP Bridge API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKeyDto } from './apiKeyDto';

export interface CreatedApiKeyDto extends ApiKeyDto {
    key: string;
}

