/**
 * MCP Bridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomMcpDto { 
    id: string;
    /**
     * Unique (per user) name — the public id becomes \"<username>-<name>\"
     */
    name: string;
    /**
     * Port the local MCP server listens on (on the user\'s machine)
     */
    port: number;
    /**
     * Optional sub-path on the local server, e.g. \"/api/mcp\" reaches http://localhost:<port>/api/mcp
     */
    subPath?: string;
    active: boolean;
    /**
     * Custom HTTP headers the agent should attach when calling the local MCP server
     */
    headers?: object;
}

