/**
 * MCP Bridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeleteMcpLogsDto { 
    /**
     * Delete exactly these log entries (bulk-select in the UI)
     */
    ids?: Array<string>;
    /**
     * Delete every log entry for this one MCP
     */
    mcpId?: string;
}

