/**
 * MCP Bridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MarketPlaceItemAssetManifestEntryDto } from './marketPlaceItemAssetManifestEntryDto';
import { MarketPlaceItemAssetChangelogDto } from './marketPlaceItemAssetChangelogDto';

export interface MarketPlaceItemAssetDto {
    id: string;
    version: string;
    fileSize: number;
    originalFilename: string;
    checksum: string;
    uploadedBy: string;
    downloadCount: number;
    fileManifest: Array<MarketPlaceItemAssetManifestEntryDto>;
    changelog: MarketPlaceItemAssetChangelogDto | null;
    createdAt: string;
}

