/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarketPlaceItemPreviewImageDto } from './marketPlaceItemPreviewImageDto';
import { MarketPlaceItemAssetDto } from './marketPlaceItemAssetDto';


export interface MarketPlaceItemDto { 
    id: string;
    name: string;
    description: string;
    ownerUsername: string;
    visibility: MarketPlaceItemDto.VisibilityEnum;
    previewImages: Array<MarketPlaceItemPreviewImageDto>;
    latestVersion?: string | null;
    totalDownloadCount: number;
    versions: Array<MarketPlaceItemAssetDto>;
    createdAt: string;
    updatedAt: string;
}
export namespace MarketPlaceItemDto {
    export const VisibilityEnum = {
        Public: 'public',
        Unlisted: 'unlisted',
        Private: 'private'
    } as const;
    export type VisibilityEnum = typeof VisibilityEnum[keyof typeof VisibilityEnum];
}


