/**
 * MCP Loop API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarketPlaceItemAssetManifestEntryDto {
    path: string;
    size: number;
    isDirectory: boolean;
    hash?: string;
    lines?: number;
}

