/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { McpLogWithContextDto } from './mcpLogWithContextDto';


export interface McpLogPageDto { 
    items: Array<McpLogWithContextDto>;
    /**
     * Total number of matching log entries across all pages
     */
    total: number;
    page: number;
    pageSize: number;
}

