/**
 * MCP Bridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface McpLogWithContextDto { 
    id: string;
    /**
     * Correlation id for this proxied request, distinct per attempt
     */
    requestId: string;
    method: string;
    path: string;
    /**
     * HTTP status returned by the agent — absent if the request failed before a response arrived
     */
    status?: number;
    /**
     * Whether the request completed with a response, regardless of status code
     */
    ok: boolean;
    /**
     * Set when the request failed (agent offline, timeout, ...)
     */
    errorMessage?: string;
    durationMs: number;
    /**
     * Body sent to the local MCP server, if any
     */
    requestBody?: object;
    /**
     * Body returned by the local MCP server — absent if the request failed before a response arrived
     */
    responseBody?: object;
    /**
     * ISO 8601 timestamp
     */
    timestamp: string;
    mcpId: string;
    mcpName: string;
}

