/**
 * MCP Bridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MyMarketPlaceDownloadDto { 
    marketPlaceItemId: string;
    itemName: string;
    /**
     * The version this user last downloaded
     */
    downloadedVersion: string;
    /**
     * The item\'s current latest version, if it still exists
     */
    latestVersion?: string | null;
    /**
     * True if the item has a newer version than the one downloaded
     */
    updateAvailable: boolean;
    downloadedAt: string;
}

