/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarketPlaceItemDto } from './marketPlaceItemDto';


export interface PaginatedMarketPlaceItemsDto { 
    items: Array<MarketPlaceItemDto>;
    total: number;
    page: number;
    pageSize: number;
}

