/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshDto { 
    username: string;
    /**
     * The refresh token issued at login/activation
     */
    refreshToken: string;
}

