/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDto { 
    /**
     * Unique username (lowercase alphanumeric / underscore, no hyphens)
     */
    username: string;
    /**
     * Password (min 8 chars)
     */
    password: string;
    /**
     * Server-side registration secret from env REGISTER_SECRET
     */
    registerSecret: string;
}

