/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenPairDto { 
    /**
     * Short-lived JWT used to authenticate API requests
     */
    accessToken: string;
    /**
     * Long-lived opaque token used to obtain a new access token via /auth/refresh
     */
    refreshToken: string;
}

