/**
 * MCP Bridge API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenPairDto {
    accessToken: string;
    refreshToken: string;
}

