/**
 * MCP Loop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateMarketPlaceItemDto { 
    name?: string;
    /**
     * Rich text (HTML) — rendered sanitized by the client
     */
    description?: string;
}

