export const CONNECTION_REGISTRY = Symbol('CONNECTION_REGISTRY');
export const PENDING_REQUEST_STORE = Symbol('PENDING_REQUEST_STORE');
export const REQUEST_ROUTER = Symbol('REQUEST_ROUTER');
export const TRANSPORT = Symbol('TRANSPORT');
export const AGENT_AUTHENTICATOR = Symbol('AGENT_AUTHENTICATOR');
